/* sitebar.js — GENERATED by scripts/build-chrome.mjs from scripts/chrome.mjs.
   Do NOT edit by hand: edit chrome.mjs and run `npm run build`. Injects the one
   site header + footer on pages that aren't pre-stamped (resume, coffee, …).
   Load BEFORE archive-menu.js + archive-subscribe.js (they wire this markup). */
(function () {
  if (!document.getElementById('carriage')) {
    var c = document.createElement('div');
    c.className = 'carriage';
    c.id = 'carriage';
    document.body.insertBefore(c, document.body.firstChild);
  }
  var carriage = document.getElementById('carriage');
  var ref = carriage.nextSibling;
  var holder = document.createElement('div');
  holder.innerHTML = "<header class=\"bar\" id=\"bar\"><div class=\"bar__row\"><a class=\"bar__home\" href=\"/\">KELLY VOHS</a><nav class=\"bar__links\"><span class=\"bar__search\" id=\"barSearch\"><input class=\"bar__searchinput\" id=\"barSearchInput\" type=\"text\" placeholder=\"find\" aria-label=\"Find\" /><button class=\"bar__mag\" aria-label=\"Search the letters\"><svg width=\"16\" height=\"16\" viewBox=\"0 0 16 16\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"1.3\" stroke-linecap=\"round\"><circle cx=\"7\" cy=\"7\" r=\"4.5\"></circle><line x1=\"10.4\" y1=\"10.4\" x2=\"14\" y2=\"14\"></line></svg></button></span><a class=\"bar__link\" href=\"/\">Photos</a><a class=\"bar__link\" href=\"/sundays\">Sundays</a><button class=\"bar__link\" data-search>Catalog</button><a class=\"bar__link\" href=\"/made\">Made</a><button class=\"bar__link\" data-subscribe>Subscribe</button></nav></div></header><nav class=\"thumb\"><button class=\"thumb__search\" data-search><span class=\"thumb__caret\"></span>find</button><button class=\"thumb__more\" data-more aria-label=\"Menu\"><i></i><i></i><i></i></button></nav>";
  while (holder.firstChild) document.body.insertBefore(holder.firstChild, ref);
  if (!document.querySelector('.foot')) {
    holder.innerHTML = "<footer class=\"foot\"><p><a href=\"/\">PHOTOS</a> · <a href=\"/sundays\">SUNDAYS</a> · <a href=\"/made\">MADE</a></p></footer>";
    document.body.appendChild(holder.firstChild);
  }
  var bar = document.getElementById('bar');
  function onScroll() {
    var h = document.documentElement, max = h.scrollHeight - h.clientHeight;
    var c = document.getElementById('carriage');
    if (c) c.style.width = (max > 0 ? (h.scrollTop / max) * 100 : 0) + '%';
    bar.classList.toggle('bar--scrolled', window.scrollY > 20);
  }
  window.addEventListener('scroll', onScroll, { passive: true });
  onScroll();
})();
