/* build-chrome.mjs — stamp the one header/footer (scripts/chrome.mjs) into the
   hand-authored static pages, and (re)write js/sitebar.js for the pages that
   inject it. Idempotent: matches the bar/footer wherever they already are and
   rewrites them from the single source.

   Run after editing chrome.mjs:  node scripts/build-chrome.mjs
   (npm run build runs this + generate-posts.mjs together). */
import { readFile, writeFile } from 'node:fs/promises';
import { bar, FOOT } from './chrome.mjs';

// Anchor the bar match on </header> so the inner <nav class="bar__links">
// doesn't trip the lazy match; the thumb nav has no nested nav.
const BAR_RE = /<header class="bar"[\s\S]*?<\/header>\s*<nav class="thumb">[\s\S]*?<\/nav>/;
const FOOT_RE = /<footer class="foot">[\s\S]*?<\/footer>/;

const PAGES = [
  { file: 'index.html', active: 'photos' },
  { file: 'pages/letters.html', active: 'sundays' },
  { file: 'pages/made.html', active: 'made' },
];

for (const p of PAGES) {
  let html = await readFile(p.file, 'utf8');
  if (!BAR_RE.test(html)) throw new Error(`no .bar found in ${p.file}`);
  if (!FOOT_RE.test(html)) throw new Error(`no .foot found in ${p.file}`);
  html = html.replace(BAR_RE, bar(p.active)).replace(FOOT_RE, FOOT);
  await writeFile(p.file, html);
}

// The legacy pages (resume, coffee, type, post, …) inject the bar at runtime.
// Generate that injector from the same source so it never drifts.
const SITEBAR = `/* sitebar.js — GENERATED by scripts/build-chrome.mjs from scripts/chrome.mjs.
   Do NOT edit by hand: edit chrome.mjs and run \`npm run build\`. Injects the one
   site header + footer on pages that aren't pre-stamped (resume, coffee, …).
   Load BEFORE archive-menu.js + archive-subscribe.js (they wire this markup). */
(function () {
  if (!document.getElementById('carriage')) {
    var c = document.createElement('div');
    c.className = 'carriage';
    c.id = 'carriage';
    document.body.insertBefore(c, document.body.firstChild);
  }
  var carriage = document.getElementById('carriage');
  var ref = carriage.nextSibling;
  var holder = document.createElement('div');
  holder.innerHTML = ${JSON.stringify(bar(null))};
  while (holder.firstChild) document.body.insertBefore(holder.firstChild, ref);
  if (!document.querySelector('.foot')) {
    holder.innerHTML = ${JSON.stringify(FOOT)};
    document.body.appendChild(holder.firstChild);
  }
  var bar = document.getElementById('bar');
  function onScroll() {
    var h = document.documentElement, max = h.scrollHeight - h.clientHeight;
    var c = document.getElementById('carriage');
    if (c) c.style.width = (max > 0 ? (h.scrollTop / max) * 100 : 0) + '%';
    bar.classList.toggle('bar--scrolled', window.scrollY > 20);
  }
  window.addEventListener('scroll', onScroll, { passive: true });
  onScroll();
})();
`;
await writeFile('js/sitebar.js', SITEBAR);

console.log('chrome stamped: ' + PAGES.map(p => p.file).join(', ') + '; js/sitebar.js written');
